import { useEffect, useState } from 'react'
import { ArrowUpRight, Check, Shuffle } from 'lucide-react'
import { useLocation } from 'wouter'
import { api, ApiError } from '@/lib/api'
import { useAuthStore } from '@/lib/store'
import { AvatarIcon, AVATAR_COLORS } from '@/components/AvatarIcon'

export default function AvatarPicker() {
  const [, navigate] = useLocation(); const setUser = useAuthStore((s) => s.setUser)
  const [avatars, setAvatars] = useState<string[]>([]); const [avatarId, setAvatarId] = useState(''); const [color, setColor] = useState(AVATAR_COLORS[0]); const [username, setUsername] = useState(''); const [available, setAvailable] = useState<boolean | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false)
  useEffect(() => { api.get<{ avatars: string[] }>('/identity/avatars').then((r) => { setAvatars(r.avatars); setAvatarId(r.avatars[0]) }); shuffle() }, [])
  async function shuffle() { const r = await api.get<{ username: string }>('/identity/username/suggest'); setUsername(r.username); checkAvailable(r.username) }
  async function checkAvailable(name: string) { if (name.length < 3) return setAvailable(null); const r = await api.get<{ available: boolean }>(`/identity/username/check?username=${encodeURIComponent(name)}`); setAvailable(r.available) }
  async function submit() { setError(null); setLoading(true); try { const res = await api.post<{ ok: boolean; user: any }>('/identity/avatar', { avatarId, avatarColor: color, username }); const user = useAuthStore.getState().user; setUser(user ? { ...user, username: res.user.username, avatarId: res.user.avatarId, onboardingStep: 'done' } : null); navigate('/plans') } catch (e) { setError(e instanceof ApiError ? e.message : 'Something went wrong') } finally { setLoading(false) } }
  return <div className="app-shell onboarding-screen"><div className="onboarding-layout"><aside className="onboarding-aside"><p className="page-kicker">Step 03 / Your vibe</p><h1 className="font-display text-5xl font-semibold tracking-tight mt-5">Make an entrance<br /><span className="editorial-serif text-punch">that feels like you.</span></h1><p className="text-muted leading-relaxed mt-6 max-w-sm">No photos, no pressure. Choose a little visual shorthand for the room.</p></aside><main className="onboarding-panel"><p className="page-kicker">Your anonymous identity</p><h2 className="font-display text-3xl font-semibold tracking-tight mt-3">Pick your look</h2><p className="text-muted mt-2">You’ll be an avatar and username until two hours before the meetup.</p><div className="avatar-preview surface-card mt-8"><AvatarIcon avatarId={avatarId} color={color} size={116} /><p className="font-display text-xl font-semibold mt-4">{username || 'your_username'}</p><span className="text-xs text-muted mt-1">anonymous, but not invisible</span></div><p className="page-kicker mt-8 mb-3">Choose a shape</p><div className="grid grid-cols-6 gap-2">{avatars.map((id) => <button key={id} onClick={() => setAvatarId(id)} className={`avatar-choice ${avatarId === id ? 'selected' : ''}`}><AvatarIcon avatarId={id} color={color} size={40} /></button>)}</div><p className="page-kicker mt-7 mb-3">Choose a color</p><div className="flex gap-3">{AVATAR_COLORS.map((c) => <button key={c} onClick={() => setColor(c)} style={{ background: c }} aria-label={`Use ${c}`} className={`color-choice ${color === c ? 'selected' : ''}`} />)}</div><label className="text-xs text-muted mb-2 mt-8 block font-semibold">Username</label><div className="flex gap-2"><input value={username} onChange={(e) => { const v = e.target.value.toLowerCase().replace(/[^a-z0-9_]/g, ''); setUsername(v); checkAvailable(v) }} className="input flex-1" /><button onClick={shuffle} className="secondary-button !min-h-0 !px-4"><Shuffle size={15} /><span className="hidden sm:inline">Shuffle</span></button></div>{available === false && <p className="text-punch text-xs mt-2">That username is taken or not allowed</p>}{available === true && <p className="text-lime text-xs mt-2 flex items-center gap-1"><Check size={13} /> Available</p>}{error && <p className="text-punch text-sm mt-4">{error}</p>}<button onClick={submit} disabled={loading || available === false || username.length < 3} className="primary-button w-full mt-8">{loading ? 'Saving…' : 'That’s me'} <ArrowUpRight size={17} /></button></main></div></div>
}
