import { useState } from 'react'
import { ArrowUpRight, LockKeyhole, ShieldCheck } from 'lucide-react'
import { useLocation } from 'wouter'
import { api, ApiError } from '@/lib/api'
import { useAuthStore } from '@/lib/store'

export default function ProfileSetup() {
  const [, navigate] = useLocation(); const setUser = useAuthStore((s) => s.setUser)
  const [email, setEmail] = useState(''); const [dob, setDob] = useState(''); const [pincode, setPincode] = useState(''); const [gender, setGender] = useState('prefer_not_to_say'); const [terms, setTerms] = useState(false); const [error, setError] = useState<string | null>(null); const [blocked, setBlocked] = useState(false); const [waitlisted, setWaitlisted] = useState(false); const [loading, setLoading] = useState(false)
  async function submit() { setError(null); if (!terms) { setError('Please accept the terms to continue'); return } setLoading(true); try { const res = await api.post<{ ok: boolean; user?: any; waitlist?: boolean }>('/auth/profile', { email, dob, pincode, gender, termsAccepted: true }); if (res.waitlist) { setWaitlisted(true); return } setUser(res.user); navigate('/onboarding/quiz') } catch (e) { if (e instanceof ApiError && e.status === 403) setBlocked(true); else setError(e instanceof ApiError ? e.message : 'Something went wrong') } finally { setLoading(false) } }
  if (blocked) return <StatusScreen icon={<ShieldCheck />} title="Not yet, delulu" body="Delulu is currently 18+. Come back when you're eligible." />
  if (waitlisted) return <StatusScreen icon={<LockKeyhole />} title="You're on the list" body="We're not in your area yet, but we'll ping you the moment we are." />
  return <div className="app-shell onboarding-screen"><div className="onboarding-layout"><aside className="onboarding-aside"><p className="page-kicker">Step 01 / The basics</p><h1 className="font-display text-5xl font-semibold tracking-tight mt-5">A little context.<br /><span className="editorial-serif text-lilac">No public profile.</span></h1><p className="text-muted leading-relaxed mt-6 max-w-sm">These details help us keep the room thoughtful and safe. They never become something people browse.</p><div className="mt-10 flex items-center gap-2 text-xs text-muted"><LockKeyhole size={14} className="text-lime" /> Kept private by default</div></aside><main className="onboarding-panel"><p className="page-kicker">Let’s make this feel like you</p><h2 className="font-display text-3xl font-semibold tracking-tight mt-3">A few basics</h2><p className="text-muted mt-2 mb-8">Private details, only used to make a better table.</p><div className="form-grid"><Field label="Email"><input value={email} onChange={(e) => setEmail(e.target.value)} type="email" className="input" placeholder="you@example.com" /></Field><Field label="Date of birth"><input value={dob} onChange={(e) => setDob(e.target.value)} type="date" className="input" /></Field><Field label="Pincode"><input value={pincode} onChange={(e) => setPincode(e.target.value.replace(/\D/g, '').slice(0, 6))} className="input" placeholder="560001" /></Field><Field label="Gender"><select value={gender} onChange={(e) => setGender(e.target.value)} className="input"><option value="female">Female</option><option value="male">Male</option><option value="non_binary">Non-binary</option><option value="prefer_not_to_say">Prefer not to say</option></select></Field></div><label className="flex items-start gap-3 text-sm text-muted mt-6"><input type="checkbox" checked={terms} onChange={(e) => setTerms(e.target.checked)} className="mt-1 accent-lilac" />I agree to the Terms and Safety Guidelines</label>{error && <p className="text-punch text-sm mt-4">{error}</p>}<button onClick={submit} disabled={loading} className="primary-button w-full mt-8">{loading ? 'Saving…' : 'Continue'} <ArrowUpRight size={17} /></button></main></div></div>
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div><label className="text-xs text-muted mb-2 block font-semibold">{label}</label>{children}</div> }
function StatusScreen({ icon, title, body }: { icon: React.ReactNode; title: string; body: string }) { return <div className="app-shell status-screen"><div className="status-card surface-card"><div className="status-icon">{icon}</div><p className="page-kicker">Delulu update</p><h1 className="font-display text-3xl font-semibold mt-3">{title}</h1><p className="text-muted leading-relaxed mt-3">{body}</p></div></div> }
